<?php

namespace Survey\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function saveStepOne( $user ){
        try
        {
            $this->getEntityManager()->persist( $user )->flush();
        }
        catch( Exception $e )
        {
            throw new \Exception($e->getMessage());
        }

        return $user;
    }
}
